# Generated by Django 4.2.1 on 2023-05-20 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_delete_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='students',
            field=models.IntegerField(default=1, verbose_name='Количество студентов'),
            preserve_default=False,
        ),
    ]
