# Generated by Django 4.2.1 on 2023-05-21 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_products_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='students',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество студентов'),
        ),
    ]
