# Generated by Django 4.2.1 on 2023-05-30 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_products_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='OSP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_images', models.ImageField(upload_to='parent_images/', verbose_name='Ваша фото')),
                ('descriptions', models.TextField(verbose_name='Ваш отзыв')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
