# Generated by Django 4.2.1 on 2023-05-30 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_osp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osp',
            name='descriptions',
            field=models.TextField(blank=True, null=True, verbose_name='Ваш отзыв'),
        ),
        migrations.AlterField(
            model_name='osp',
            name='parent_images',
            field=models.ImageField(blank=True, null=True, upload_to='parent_images/', verbose_name='Ваша фото'),
        ),
    ]
