# Generated by Django 4.2.1 on 2023-05-21 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0002_setting_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='about',
            field=models.TextField(default=1, verbose_name='О нас'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='email',
            field=models.EmailField(default=1, max_length=254, unique=True, verbose_name='Email Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='resource',
            field=models.TextField(default=1, verbose_name='Наши ресурсы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='tel',
            field=models.CharField(default=2, max_length=30, verbose_name='Мои контакты'),
            preserve_default=False,
        ),
    ]
