# Generated by Django 4.2.1 on 2023-05-25 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0004_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Achievements',
        ),
    ]
