# Generated by Django 4.2.1 on 2023-05-25 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0005_rename_student_achievements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievements',
            name='course',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Всего курсов'),
        ),
        migrations.AlterField(
            model_name='achievements',
            name='positions',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Глобальная позиция'),
        ),
        migrations.AlterField(
            model_name='achievements',
            name='students',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Всего студентов'),
        ),
    ]
